[package]
name = "seekr"
version = "0.0.1"
edition = "2021"
description = " A spotlight like search util for linux"
license = "MIT"
repository = "https://github.com/luxluth/fsearch"
readme = "../README.md"
homepage = "https://github.com/luxluth/fsearch"
categories = ["tools"]
keywords = ["fsearch", "spotlight", "gui"]
authors = ["luxluth <delphin.blehoussi93@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exmex = "0.20.3"
gtk = { version = "0.9.4", package = "gtk4", features = ["v4_14"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
dbus = "0.9.7"
freedesktop-desktop-entry = "0.7.5"
fuzzy-matcher = "0.3.7"
async-channel = "2.3.1"
tokio = { version = "1.42.0", features = ["full"] }
linicon = {version = "2.3.0", features = ["expand-paths"] }
lazy_static = "1.5.0"
fragile = "2.0.0"
ini-roundtrip = "0.2.0"
rust-i18n = "3.1.2"

[profile.release]
lto = true
codegen-units = 1
