[package]
name = "fsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
exmex = "0.17.5"
gdk = { version = "0.7.3", package = "gdk4", features = ["v4_12"] }
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
open = "5.0.0"

